### PR TITLE
resolve .crypto domains

### PR DESCRIPTION
**Pull request by JohnnyJumper**
Please take a look at it

### CODE REVIEW

**Comment by mvlabat** [comment]
I'm not sure it's a good idea to have two almost identical guides, with the only difference that instead of mentioning .zil we mention .crypto. I'd put this on hold until we merge the guide about .zil and then decide what to do about .crypto.

**Comment by mvlabat** [comment]
I actually think we could incorporate these two guides into one, and we could use tabs for the code that differ or something like that.

**Review by DeRain — CHANGES_REQUESTED** [review]
As we've discussed the changes are similar as for .zil article https://github.com/unstoppabledomains/docs/pull/35/files

**Review by DeRain — APPROVED** [review]
@JohnnyJumper Nice job! Please, do not merge it to master since we will publish this to Medium

**Pull request closed without merging**
